version: "3.7"
services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - target: 27017
        published: ${OFF_MONGO_PORT_PUBLISHED}
    volumes:
      - type: bind
        source: ./docker/mongo
        target: /etc/mongo
      - type: volume
        source: mongo
        target: /data/db
    environment:
      - TZ=${OFF_TZ}
    command: --config /etc/mongo/mongod.conf
  apache:
    build:
      context: docker/apache
      args:
        - off_root=${OFF_ROOT}
    container_name: apache
    depends_on:
      - mongo
    ports:
      - target: ${OFF_APACHE_PORT}
        published: ${OFF_APACHE_PORT_PUBLISHED}
      - target: 8082
        published: ${OFF_PHPMEMCACHEDADMIN_PORT_PUBLISHED}
    volumes:
      - type: bind
        source: ./docker/apache/etc/apache2/conf-enabled
        target: /etc/apache2/conf-enabled
      - type: bind
        source: ./docker/apache/etc/apache2/sites-enabled
        target: /etc/apache2/sites-enabled
      - type: bind
        source: ./docker/apache/etc/apache2/ports.conf
        target: /etc/apache2/ports.conf
      - type: bind
        source: ./docker/phpmemcachedadmin-1.3.0/Config
        target: /var/www/phpmemcachedadmin-1.3.0/Config
      - type: bind
        source: ./openfoodfacts-server
        target: ${OFF_ROOT}
      - type: volume
        source: images_products
        target: ${OFF_ROOT}/html/images/products
      - type: volume
        source: logs
        target: ${OFF_ROOT}/logs
      - type: volume
        source: products
        target: ${OFF_ROOT}/products
      - type: volume
        source: tmp
        target: ${OFF_ROOT}/tmp
      - type: volume
        source: users
        target: ${OFF_ROOT}/users
      - type: bind
        source: ./openfoodfacts-server/lib/ProductOpener/Config_off.pm
        target: ${OFF_ROOT}/lib/ProductOpener/Config.pm
      - type: bind
        source: ./openfoodfacts-server/lib/ProductOpener/Config2_sample_docker.pm
        target: ${OFF_ROOT}/lib/ProductOpener/Config2.pm
    environment:
      - OFF_ROOT=${OFF_ROOT}
      - PERL5LIB=${OFF_ROOT}/lib
      - OFF_DOCUMENT_ROOT=${OFF_ROOT}/html
      - OFF_APACHE_PORT=${OFF_APACHE_PORT}
      - OFF_SERVER_NAME=${OFF_SERVER_NAME}
      - OFF_SSL_SUBDOMAINS=${OFF_SSL_SUBDOMAINS}
      - OFF_MONGODB_USER=${OFF_MONGODB_USER}
      - OFF_MONGODB_HOST=${OFF_MONGODB_HOST}
      - OFF_MEMCACHE_SERVERS=${OFF_MEMCACHE_SERVERS}
      - OFF_PHPMEMCACHEDADMIN_PORT=${OFF_PHPMEMCACHEDADMIN_PORT}
      - OFF_SERVER_ADMIN=${OFF_SERVER_ADMIN}
      - TZ=${OFF_TZ}
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    depends_on:
      - apache
    ports:
      - target: ${OFF_NGINX_PORT}
        published: ${OFF_NGINX_PORT_PUBLISHED}
    volumes:
      - type: bind
        source: ./openfoodfacts-server/html
        target: ${OFF_ROOT}/html
      - type: bind
        source: ./docker/nginx/etc/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: volume
        source: images_products
        target: ${OFF_ROOT}/html/images/products
    environment:
      - DOLLAR=${DOLLAR}
      - OFF_APACHE_PORT=${OFF_APACHE_PORT}
      - OFF_DOCUMENT_ROOT=${OFF_ROOT}/html
      - OFF_NGINX_PORT=${OFF_NGINX_PORT}
      - OFF_SERVER_NAME=${OFF_SERVER_NAME}
      - TZ=${OFF_TZ}
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/off-proxy.template > /etc/nginx/conf.d/off-proxy.conf && nginx -g 'daemon off;'"
volumes:
  mongo:
  images_products:
  logs:
  products:
  tmp:
  users:
  users_emails:
